import homeController from './HomeController';
import authController from './AuthController';
import userController from './UserController';
import contactController from './ContactController';
import notificationController from './NotificationController';
import messageController from './MessageController';
export const home = homeController;
export const auth = authController;
export const user = userController;
export const contact = contactController;
export const notification = notificationController;
export const message = messageController;
