import authService from "./AuthService";
import userService from './UserService';
import contactService from './ContactService';
import notificationService from './NotificationService';
import messageService from './MessageService';
export const auth = authService; 
export const user = userService;
export const contact = contactService;
export const notification = notificationService;
export const message = messageService;
